# Generated by Django 3.0.6 on 2020-05-20 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200513_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('c5f1c2f2-29cf-4f2e-803f-b4f4b5ebf0a9'), editable=False),
        ),
    ]
