# Generated by Django 3.0.6 on 2020-05-21 01:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20200520_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('3d8238bc-cc32-4526-87d9-994876fcbb4f'), editable=False),
        ),
    ]
