# Generated by Django 3.0.6 on 2020-05-21 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200521_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('b635f35c-cc79-46df-b12d-9d903285819b'), editable=False),
        ),
    ]
