# Generated by Django 3.0.6 on 2020-05-21 03:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200521_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('c30e60c3-e51d-4aca-89bd-9380bd1b19ee'), editable=False),
        ),
    ]
