# Generated by Django 3.0.6 on 2020-05-21 03:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20200521_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('d29722d3-8cf0-4c9e-bcd7-d05828a0fc17'), editable=False),
        ),
    ]
