# Generated by Django 3.0.6 on 2020-05-21 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20200521_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('bc966b84-5f84-4129-acf3-de301c3152b8'), editable=False),
        ),
    ]
