# Generated by Django 3.0.6 on 2020-05-21 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20200521_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.UUIDField(default=uuid.UUID('0c3e6335-44de-4659-a6d4-4469a0540b4e'), editable=False),
        ),
    ]
